services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
